url: https://ssesayjr.github.io
baseurl: /profile/

# Site settings
title: Welcome!  
email: samuel.sesay.jr@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name:
  pic: 1
  position: 
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title:
      url: #

- name: 
  pic: 2
  position:
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

- name: 
  pic: 3
  position: 
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: email
    url: mailto: samuel.sesay.jr@gmail.com
  - title: linkedin 
    url: https://www.linkedin.com/in/sbsesay/
  - title: github
    url: https://github.com/ssesayjr

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
